# Mail Config
spring.mail.host=pro.turbo-smtp.com
spring.mail.port=587
spring.mail.username=supmtimail@yahoo.com
spring.mail.password=nurqnUUrXPIWvR6
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Gateway Routes (shared)
server.port=8084
